version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    default_assignees:
      - "haxorof"
    default_reviewers:
      - "haxorof"
    update_schedule: "daily"
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    default_assignees:
      - "haxorof"
    default_reviewers:
      - "haxorof"
