name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 0'

env:
  IMAGE_NAME: haxorof/ansible-lint
  LATEST_OS: alpine
  LATEST_VERSION: v6

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [almalinux, alpine]
        version: [v5, v6]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          cp requirements/${MATRIX_VERSION}/requirements.txt requirements/requirements.txt
          TAGS="${IMAGE_NAME}:${MATRIX_VERSION}-${MATRIX_OS}"
          TEST_TAG="${TAGS}"
          if [[ "$MATRIX_OS" == "$LATEST_OS" ]]; then
            TAGS="${TAGS},${IMAGE_NAME}:$MATRIX_VERSION"
            if [[ "$MATRIX_VERSION" == "$LATEST_VERSION" ]]; then
              TAGS="${TAGS},${IMAGE_NAME}:latest-${MATRIX_OS},${IMAGE_NAME}:latest"
            fi
          elif [[ "$MATRIX_VERSION" == "$LATEST_VERSION" ]]; then
            TAGS="${TAGS},${IMAGE_NAME}:latest-${MATRIX_OS}"
          fi
          echo "test_tag=${TEST_TAG}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        env:
          MATRIX_OS: ${{ matrix.os }}
          MATRIX_VERSION: ${{ matrix.version }}

      - name: Lint Dockerfile
        uses: docker://replicated/dockerfilelint:latest
        with:
          args: Dockerfile.${{ matrix.os }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          load: true
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
          tags: ${{ steps.prep.outputs.test_tag }}
          context: .
          file: ./Dockerfile.${{ matrix.os }}

      - name: Test built image
        run: |
          docker run --rm -v ${PWD}/test/${{ matrix.version }}:/mnt:ro ${{ steps.prep.outputs.test_tag }} -vv --force-color .

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        if: ${{ endsWith(github.ref, '/master') }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
          tags: ${{ steps.prep.outputs.tags }}
          context: .
          file: ./Dockerfile.${{ matrix.os }}
          push: ${{ endsWith(github.ref, '/master') }}

  dependabot:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    needs: build_push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.dependabot-metadata.outputs.package-ecosystem == 'github_actions'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  update_docker_hub_description:
    if: ${{ endsWith(github.ref, '/master') }}
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
